#!/usr/bin/env python3
"""Fetch order.searchList and emit payment-events JSON in one step.

Usage:
  python scripts/doudian_fetch_payment_events.py ^
    --live-started-at "2026/07/28 08:15:49" ^
    --live-ended-at "2026/07/28 15:44:39" ^
    --output payment-events.json

Stdout receives only JSON when --output is omitted.
Progress logs go to stderr.
"""

from __future__ import annotations

import argparse
import contextlib
import io
import json
import os
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from doudian_fetch_orders import (  # noqa: E402
    DEFAULT_ENV,
    DEFAULT_SDK,
    DEFAULT_TOKEN,
    DoudianApiError,
    fetch_orders,
    filter_orders_by_pay_time,
    fmt_local,
    load_kv_file,
    parse_time,
)
from doudian_order_events import extract_events, summarize  # noqa: E402

CN_TZ = timezone(timedelta(hours=8))


def write_token_env_atomic(output: Path, payload: dict[str, str]) -> None:
    """Replace the token file without leaving a half-written credential file."""
    lines = [
        "# generated by automatic Doudian token refresh — do not commit",
        f"DOUYIN_OPEN_ACCESS_TOKEN={payload['access_token']}",
        f"DOUYIN_OPEN_REFRESH_TOKEN={payload.get('refresh_token', '')}",
        f"DOUYIN_OPEN_TOKEN_EXPIRES_IN={payload.get('expires_in', '')}",
        f"DOUYIN_OPEN_SHOP_ID={payload.get('shop_id', '')}",
        f"DOUYIN_OPEN_SHOP_NAME={payload.get('shop_name', '')}",
    ]
    output.parent.mkdir(parents=True, exist_ok=True)
    temp_path = output.with_name(f".{output.name}.{os.getpid()}.tmp")
    try:
        temp_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        os.replace(temp_path, output)
    finally:
        temp_path.unlink(missing_ok=True)


def refresh_access_token(
    *,
    env_file: Path,
    sdk_path: Path,
    token_file: Path,
    token_env: dict[str, str],
) -> str:
    refresh_token = token_env.get("DOUYIN_OPEN_REFRESH_TOKEN", "").strip()
    shop_id = token_env.get("DOUYIN_OPEN_SHOP_ID", "").strip()
    if not refresh_token and not shop_id:
        raise RuntimeError("抖店授权已过期，且缺少 refresh token 和店铺 ID，请重新绑定抖店账号")

    configure_sdk(env_file, sdk_path)
    sys.path.insert(0, str(sdk_path))
    from doudian.core.AccessTokenBuilder import AccessTokenBuilder

    token = None
    if refresh_token:
        with contextlib.redirect_stdout(io.StringIO()):
            token = AccessTokenBuilder.refreshToken(refresh_token)
    if token is None or not token.isSuccess():
        if not shop_id:
            response = token.accessTokenResp
            sub_message = getattr(response, "sub_msg", "") or getattr(response, "msg", "")
            raise RuntimeError(f"抖店授权自动刷新失败，请重新绑定抖店账号：{sub_message}")

        # Self-use apps can issue a new token for an already-bound shop even
        # after the saved refresh token has expired.
        with contextlib.redirect_stdout(io.StringIO()):
            token = AccessTokenBuilder.buildTokenByShopId(shop_id)
        response = token.accessTokenResp
        if not token.isSuccess():
            sub_message = getattr(response, "sub_msg", "") or getattr(response, "msg", "")
            raise RuntimeError(f"抖店授权已失效，请重新绑定抖店账号：{sub_message}")

    response = token.accessTokenResp

    response_data = getattr(response, "data", None)
    if not isinstance(response_data, dict):
        response_data = {}
    access_token = str(response_data.get("access_token") or "").strip()
    if not access_token:
        raise RuntimeError("抖店授权自动刷新未返回 access token，请重新绑定抖店账号")

    payload = {
        "access_token": access_token,
        "refresh_token": str(response_data.get("refresh_token") or refresh_token),
        "expires_in": str(response_data.get("expires_in") or ""),
        "shop_id": str(
            response_data.get("shop_id") or token_env.get("DOUYIN_OPEN_SHOP_ID", "")
        ),
        "shop_name": str(
            response_data.get("shop_name") or token_env.get("DOUYIN_OPEN_SHOP_NAME", "")
        ),
    }
    write_token_env_atomic(token_file, payload)
    return access_token


def fetch_orders_with_auto_refresh(
    *,
    access_token: str,
    token_env: dict[str, str],
    token_file: Path,
    env_file: Path,
    sdk_path: Path,
    create_time_start: int,
    create_time_end: int,
    order_status: str | None,
    page_size: int,
) -> list[dict[str, Any]]:
    request = {
        "sdk_path": sdk_path,
        "create_time_start": create_time_start,
        "create_time_end": create_time_end,
        "order_status": order_status,
        "page_size": page_size,
    }
    try:
        return fetch_orders(access_token=access_token, **request)
    except DoudianApiError as error:
        if not error.is_access_token_expired:
            raise

    print("Doudian access token expired; refreshing once...", file=sys.stderr)
    refreshed_token = refresh_access_token(
        env_file=env_file,
        sdk_path=sdk_path,
        token_file=token_file,
        token_env=token_env,
    )
    print("Doudian access token refreshed; retrying order.searchList...", file=sys.stderr)
    return fetch_orders(access_token=refreshed_token, **request)


def configure_sdk(env_file: Path, sdk_path: Path) -> None:
    app_env = load_kv_file(env_file) if env_file.is_file() else {}
    sys.path.insert(0, str(sdk_path))
    from doudian.core.DoudianOpConfig import GlobalConfig

    app_key = app_env.get("DOUYIN_OPEN_APP_KEY") or app_env.get("APP_KEY")
    app_secret = app_env.get("DOUYIN_OPEN_APP_SECRET") or app_env.get("APP_SECRET")
    if not app_key or not app_secret:
        raise RuntimeError(f"Missing DOUYIN_OPEN_APP_KEY/SECRET in {env_file}")
    GlobalConfig.appKey = app_key
    GlobalConfig.appSecret = app_secret


def main() -> int:
    parser = argparse.ArgumentParser(description="Fetch Doudian orders and build payment-events JSON")
    parser.add_argument("--env-file", type=Path, default=DEFAULT_ENV)
    parser.add_argument("--token-file", type=Path, default=DEFAULT_TOKEN)
    parser.add_argument("--sdk-path", type=Path, default=DEFAULT_SDK)
    parser.add_argument("--live-started-at", required=True)
    parser.add_argument("--live-ended-at", required=True)
    parser.add_argument("--shop-id", default="")
    parser.add_argument("--shop-name", default="")
    parser.add_argument("--create-buffer-before", type=int, default=259200)
    parser.add_argument("--create-buffer-after", type=int, default=86400)
    parser.add_argument("--page-size", type=int, default=50)
    parser.add_argument("--output", type=Path, help="Write JSON here; default stdout")
    args = parser.parse_args()

    if not args.sdk_path.is_dir():
        print(f"SDK not found: {args.sdk_path}", file=sys.stderr)
        return 1
    if not args.token_file.is_file():
        print(f"Token file not found: {args.token_file}", file=sys.stderr)
        print("Run scripts/doudian_get_token.py first.", file=sys.stderr)
        return 1
    if not args.env_file.is_file():
        print(f"Env file not found: {args.env_file}", file=sys.stderr)
        return 1

    pay_start = parse_time(args.live_started_at)
    pay_end = parse_time(args.live_ended_at)
    if pay_start >= pay_end:
        print("live-started-at must be before live-ended-at", file=sys.stderr)
        return 1

    create_start = pay_start - args.create_buffer_before
    create_end = pay_end + args.create_buffer_after

    token_env = load_kv_file(args.token_file)
    access_token = token_env.get("DOUYIN_OPEN_ACCESS_TOKEN", "")
    if not access_token:
        print("Missing DOUYIN_OPEN_ACCESS_TOKEN in token file", file=sys.stderr)
        return 1

    configure_sdk(args.env_file, args.sdk_path)

    print(
        "Fetching order.searchList\n"
        f"  live window: {fmt_local(pay_start)} .. {fmt_local(pay_end)}\n"
        f"  create_time: {fmt_local(create_start)} .. {fmt_local(create_end)}",
        file=sys.stderr,
    )

    try:
        raw_orders = fetch_orders_with_auto_refresh(
            access_token=access_token,
            token_env=token_env,
            token_file=args.token_file,
            env_file=args.env_file,
            sdk_path=args.sdk_path,
            create_time_start=create_start,
            create_time_end=create_end,
            # Keep every order that has a pay_time in the live window.  A
            # later refund/close (status 4) must not erase the historical
            # purchase signal used to locate the streamer's deal speech.
            order_status=None,
            page_size=args.page_size,
        )
    except DoudianApiError as error:
        if error.is_access_token_expired:
            print("抖店授权已失效，自动刷新后仍不可用，请重新绑定抖店账号", file=sys.stderr)
        else:
            print(f"抖店订单接口失败：{error}", file=sys.stderr)
        return 2
    except RuntimeError as error:
        print(str(error), file=sys.stderr)
        return 2
    orders, pay_filter_stats = filter_orders_by_pay_time(raw_orders, pay_start, pay_end)

    shop_id = (args.shop_id or token_env.get("DOUYIN_OPEN_SHOP_ID", "")).strip()
    shop_name = (args.shop_name or token_env.get("DOUYIN_OPEN_SHOP_NAME", "")).strip()
    if shop_id:
        orders = [order for order in orders if str(order.get("shop_id", "")) == shop_id]

    import tempfile

    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".json",
        delete=False,
        encoding="utf-8",
    ) as handle:
        json.dump(
            {
                "shops": [
                    {
                        "shop_id": shop_id,
                        "shop_name": shop_name,
                        "orders": orders,
                    }
                ]
            },
            handle,
            ensure_ascii=False,
        )
        orders_path = Path(handle.name)

    try:
        events, shop_meta = extract_events(
            orders_path,
            pay_start,
            shop_id=shop_id or None,
            shop_name=shop_name or None,
        )
    finally:
        orders_path.unlink(missing_ok=True)

    current_valid_events = [
        event for event in events if str(event.get("order_status") or "") in {"2", "3", "5"}
    ]
    closed_or_refunded_events = [
        event for event in events if str(event.get("order_status") or "") == "4"
    ]

    result: dict[str, Any] = {
        "fetched_at": datetime.now(CN_TZ).isoformat(),
        "source_label": "order.searchList",
        "summary": summarize(events, pay_start, shop_meta),
        "events": events,
        "orders_payload": {
            "shops": [
                {
                    "shop_id": shop_id,
                    "shop_name": shop_name,
                    "orders": orders,
                }
            ]
        },
        "stats": {
            "raw_order_count": len(raw_orders),
            "kept_order_count": len(orders),
            "event_count": len(events),
            "status": {
                "current_valid_event_count": len(current_valid_events),
                "current_valid_amount_fen": sum(
                    event.get("pay_amount_fen") or 0 for event in current_valid_events
                ),
                "closed_or_refunded_event_count": len(closed_or_refunded_events),
                "closed_or_refunded_amount_fen": sum(
                    event.get("pay_amount_fen") or 0 for event in closed_or_refunded_events
                ),
            },
            "pay_filter": pay_filter_stats,
            "query": {
                "live_started_at": fmt_local(pay_start),
                "live_ended_at": fmt_local(pay_end),
                "create_time_start_local": fmt_local(create_start),
                "create_time_end_local": fmt_local(create_end),
                "shop_id": shop_id or None,
                "order_status": "all_paid_in_window",
            },
        },
    }

    text = json.dumps(result, ensure_ascii=False, indent=2)
    if args.output:
        args.output.write_text(text + "\n", encoding="utf-8")
        print(f"Wrote {len(events)} payment events -> {args.output}", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
