#!/usr/bin/env python3
"""Exchange Doudian shop authorization for access_token using Desktop .env + SDK.

Reads credentials from (first match):
  1. --env-file path
  2. DOUYIN_ENV_FILE env var
  3. d:\\Desktop\\.env

Required in .env:
  DOUYIN_OPEN_APP_KEY=...
  DOUYIN_OPEN_APP_SECRET=...

Then choose one mode:

  Tool app (工具型) — get code from console:
    https://op.jinritemai.com/console → 常用工具 → 测试账号管理 → 复制「授权 code」
    python scripts/doudian_get_token.py --mode code --code "<授权code>"

  Self-use app (自用型) — shop already bound in console:
    python scripts/doudian_get_token.py --mode self --shop-id "<shop_id>"

  Refresh existing token:
    python scripts/doudian_get_token.py --mode refresh --refresh-token "<refresh_token>"

Successful tokens are written to the output file (default: same dir as .env, doudian_token.env).
Never commit token files to git.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


DEFAULT_ENV = Path(r"d:\Desktop\.env")
DEFAULT_SDK = Path(r"d:\Desktop\doudian-sdk-python-1.1.0-20260724091610\sdk-python")


def load_dotenv(path: Path) -> dict[str, str]:
    if not path.is_file():
        raise FileNotFoundError(f".env not found: {path}")

    env: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        value = value.strip()
        if (value.startswith('"') and value.endswith('"')) or (
            value.startswith("'") and value.endswith("'")
        ):
            value = value[1:-1]
        else:
            # tolerate a stray trailing quote from hand-edited .env files
            value = value.rstrip('"').lstrip('"')
        env[key.strip()] = value
    return env


def resolve_sdk_path(cli_path: str | None) -> Path:
    if cli_path:
        return Path(cli_path)
    env_path = os.environ.get("DOUDIAN_SDK_PATH", "").strip()
    if env_path:
        return Path(env_path)
    return DEFAULT_SDK


def mask(value: str, keep: int = 4) -> str:
    if len(value) <= keep * 2:
        return "***"
    return f"{value[:keep]}...{value[-keep:]}"


def write_token_env(output: Path, payload: dict[str, str]) -> None:
    lines = [
        "# generated by scripts/doudian_get_token.py — do not commit",
        f"DOUYIN_OPEN_ACCESS_TOKEN={payload['access_token']}",
        f"DOUYIN_OPEN_REFRESH_TOKEN={payload.get('refresh_token', '')}",
        f"DOUYIN_OPEN_TOKEN_EXPIRES_IN={payload.get('expires_in', '')}",
        f"DOUYIN_OPEN_SHOP_ID={payload.get('shop_id', '')}",
        f"DOUYIN_OPEN_SHOP_NAME={payload.get('shop_name', '')}",
    ]
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Get Doudian access_token")
    parser.add_argument("--env-file", type=Path, default=None)
    parser.add_argument("--sdk-path", type=str, default=None)
    parser.add_argument(
        "--mode",
        choices=("code", "self", "refresh"),
        default="code",
        help="code=工具型(authorization_code); self=自用型(authorization_self)",
    )
    parser.add_argument("--code", help="Authorization code from console (10 min TTL)")
    parser.add_argument("--shop-id", help="Shop id for self-use apps")
    parser.add_argument("--refresh-token", help="Refresh token for --mode refresh")
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Where to write token env (default: <env-dir>/doudian_token.env)",
    )
    args = parser.parse_args()

    env_path = args.env_file or Path(os.environ.get("DOUYIN_ENV_FILE", DEFAULT_ENV))
    env = load_dotenv(env_path)
    app_key = env.get("DOUYIN_OPEN_APP_KEY") or env.get("APP_KEY")
    app_secret = env.get("DOUYIN_OPEN_APP_SECRET") or env.get("APP_SECRET")

    if not app_key or not app_secret:
        print("Missing DOUYIN_OPEN_APP_KEY / DOUYIN_OPEN_APP_SECRET in .env", file=sys.stderr)
        return 1

    sdk_path = resolve_sdk_path(args.sdk_path)
    if not sdk_path.is_dir():
        print(f"SDK not found: {sdk_path}", file=sys.stderr)
        return 1

    sys.path.insert(0, str(sdk_path))
    from doudian.core.AccessTokenBuilder import AccessTokenBuilder
    from doudian.core.DoudianOpConfig import GlobalConfig

    GlobalConfig.appKey = app_key
    GlobalConfig.appSecret = app_secret

    print(f"Using app_key={mask(app_key)} env={env_path} sdk={sdk_path}")

    if args.mode == "code":
        code = args.code or env.get("DOUYIN_OPEN_AUTH_CODE")
        if not code:
            print(
                "Tool app needs an authorization code.\n"
                "1. Open https://op.jinritemai.com/console\n"
                "2. 常用工具 → 测试账号管理 → copy 「授权 code」\n"
                "3. Re-run: python scripts/doudian_get_token.py --mode code --code \"<code>\"",
                file=sys.stderr,
            )
            return 1
        token = AccessTokenBuilder.buildTokenByCode(code)
    elif args.mode == "self":
        shop_id = args.shop_id or env.get("DOUYIN_OPEN_SHOP_ID")
        if not shop_id:
            print(
                "Self-use app needs shop_id. Bind shop in console, then:\n"
                "python scripts/doudian_get_token.py --mode self --shop-id \"<shop_id>\"",
                file=sys.stderr,
            )
            return 1
        token = AccessTokenBuilder.buildTokenByShopId(shop_id)
    else:
        refresh = args.refresh_token or env.get("DOUYIN_OPEN_REFRESH_TOKEN")
        if not refresh:
            print("Missing --refresh-token or DOUYIN_OPEN_REFRESH_TOKEN", file=sys.stderr)
            return 1
        token = AccessTokenBuilder.refreshToken(refresh)

    resp = token.accessTokenResp
    if not token.isSuccess():
        print("Token request failed:", file=sys.stderr)
        print("  code:", getattr(resp, "code", None), file=sys.stderr)
        print("  msg:", getattr(resp, "msg", None), file=sys.stderr)
        print("  sub_code:", getattr(resp, "sub_code", None), file=sys.stderr)
        print("  sub_msg:", getattr(resp, "sub_msg", None), file=sys.stderr)
        print("  data:", getattr(resp, "data", None), file=sys.stderr)
        return 2

    payload = {
        "access_token": token.getAccessToken(),
        "refresh_token": token.getRefreshToken(),
        "expires_in": str(token.getExpiresIn()),
        "shop_id": str(token.getShopId()),
        "shop_name": token.getShopName(),
    }

    output = args.output or env_path.parent / "doudian_token.env"
    write_token_env(output, payload)

    print("Success.")
    print(f"  shop_id:   {payload['shop_id']}")
    print(f"  shop_name: {payload['shop_name']}")
    print(f"  expires_in: {payload['expires_in']} seconds")
    print(f"  access_token: {mask(payload['access_token'])}")
    print(f"  refresh_token: {mask(payload.get('refresh_token', ''))}")
    print(f"  saved to: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
